spring.application.name=employee-mood-system

spring.datasource.url=jdbc:postgresql://sxterm.mat.umk.pl:5432/mprzystawski
spring.datasource.username=mprzystawski
spring.datasource.password=employeeMoodSystem

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

